---
version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - arch=${ARCH:-x86_64}
    command: sh localnet.sh
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
